= “Ingegneria del Software” | 2023-2024
Docente: Prof. Angelo Furfaro; Studente: Stefano Scarcelli - 230668 <scrsfn02t15d086u@studenti.unical.it>
Documento Finale (D3) | {docdate}
:doctype: article
:title-separator: |
:toc:

.*List of Challenging/Risky Requirements or Tasks*
|===
^.^|Challenging Task ^.^|Date the task is identified ^.^|Date the challenge is resolved ^.^|Explanation on how the challenge has been managed

.^|Impostazione del _progetto_ con sistema di automazione di *build*, *test* e gestore delle *dipendenze*
^.^|17/06/2024
^.^|18/06/2024
|Tentativo di uso di *Maven*, poi scartato per via di errori nella gestione della dependency di _JavaFX_, e scelta della soluzione tramite *Gradle*

|
|
|
|

|===

== A. Stato dell’Arte
_Analizzate sistemi esistenti, prendete spunto da cio’ che esiste._

=== A.1 Web application:
* *Snakes and Ladders* (https://www.crazygames.com/game/snakes-and-ladders[Play on CrazyGames])
** Presenza di due modalità con rappresentazione grafica differente;
** Possibilità di giocare *Player VS Player* (tutti contro tutti) o *Player VS Computer* (1 VS Computer);
** Possibilità di giocare da *2* a *6* _giocatori_;
** Animazione lancio di dadi (pre renderizzata, non in real time);
** Indicatore di _turno_;
** Piccola schermata di spiegazione delle *regole di gioco*;
* *Play Snakes and Ladders* (https://www.calculators.org/games/snakes-and-ladders/[Calculators.org])
** Grafica stilizzata;
** Modalità *Single Player* e *Multi Player*;
** Possibilità di giocare da *2* a *4* _giocatori_;
** Effetti sonori;
** *Leader board*;
** Indicatore di _turno_;
* *Snakes And Ladders* (https://www.playonlinedicegames.com/snakesandladders[Playonlinedicegames.com])
** Possibilità di giocare *Player VS Player* (1 VS 1) o *Player VS Computer* (1 VS Computer);
** Interfaccia semplice;
** Animazioni di turno rapide;
* *Snakes And Ladders* (https://www.alc.ca/content/alc/en/play-online/instant-win-games/snakes-ladders.html[Atlantic Lottery])
** Gioco d'azzardo;

=== A.2 PC & Game console:
* *Snakes & Ladders+ : Board Game* (https://www.xbox.com/it-IT/games/store/snakes-ladders-board-game-pc-xbox/9P1K912MHQKB[Link])
** Tema marino;
** Possibilità di giocare *Player VS Player* (1 VS 1) o *Player VS Computer* (1 VS Computer);
** Diversi _tabelloni_;
** Spiegazione esaustiva delle *regole di gioco*;
* *Snake and Ladder Game for Windows 10* (https://download.cnet.com/snake-and-ladder-game-for-windows-10/3000-2111_4-77568851.html[Link])
** Giocabile da *2* a _più giocatori_ (non specificato nella descrizione);
** Tabellone da *100* _caselle_;
** Possibilità di scegliere il *colore* del _tabellone_ tra vari preset;

=== A.3 Mobile game:
* *Snakes and Ladders* (https://play.google.com/store/apps/details?id=ir.Hadiware.Snake_Ladder&hl=en_US[Link])
** Vari *temi* e *tipologie* di _tabelloni_;
** Possibilità di giocare da *2* a *4* _giocatori_;
** Possibilità di selezionare _individualmente_ per pedina se _escluderla_, inserirla come *giocatore* o inserirla come *computer*;
* *Snakes and Ladders Board Games* (https://play.google.com/store/apps/details?id=com.idz.snakes.and.ladders.dice.board.games&hl=en_US[Link])
** Grafica 3D;
** Gioco a *livelli*;
** Il _tabellone_ è sostituito con un *percorso* di una _mappa a tema_;

== B. Raffinamento dei Requisiti
_A partire dai servizi minimali richiesti, raffinate la descrizione dei servizi offerti dal vostro applicativo. Descrivete anche I requisiti non funzionali._

=== B.1 Servizi (con prioritizzazione)
_Descrivete in *dettaglio* i servizi offerti dal vostro Sistema, insieme a quelli che ritenete siano le soluzioni concettuali necessarie. In questa fase, non fate riferimento ad alcuna tecnologia specifica. Se volete, intervistate stakeholder e collezionate dati dal web o da altre sorgenti. Dovete acquisire una conoscenza avanzata dei problemi associate ai vostri servizi. Assegnate un ID a ciascun servizio. Prioritizzate inoltre i servizi in base a due scale: Importanza alta, media, bassa. Complessità alta, media, bassa._

. _Impostazione della partita da simulare:_
.. Interfaccia di setup (*Importanza* _media_, *Complessità* _bassa_)
.. Salvare/caricare setup (*Importanza* _bassa_, *Complessità* _media_)
. _Simulazione della partita:_
.. Avanzamento automatico e manuale (*Importanza* _alta_, *Complessità* _bassa_)
.. Lancio dei dai (*Importanza* _alta_, *Complessità* _media_)
.. Regole di movimento delle pedine (*Importanza* _alta_, *Complessità* _alta_)
.. Mazzo di carte (*Importanza* _media_, *Complessità* _alta_)
. _Visualizzazione dei turni simulati:_
.. Rappresentazione del tabellone (*Importanza* _media_, *Complessità* _alta_)
.. Rappresentazione delle pedine sul tabellone (*Importanza* _media_, *Complessità* _bassa_)
. _Visualizzazione dei risultati della partita:_
.. Vincitore della partita (*Importanza* _alta_, *Complessità* _bassa_)
.. Classifica finale (*Importanza* _bassa_, *Complessità* _bassa_)

.Importanza/Complessità dei servizi
[cols="1,5a"]
|===
| ^.^|Complessità

^.^|*Importanza*
|

!===
! ^.^!Bassa ^.^!Media ^.^!Alta

^.^!*Bassa*
!4.b
!1.b
!

^.^!*Media*
!1.a, 3.b
!
!2.d, 3.a

^.^!*Alta*
!2.a, 4.a
!2.b
!2.c

!===

|===

=== B.2 Requisiti non Funzionali
_Elencare i requisiti non funzionali più’ importanti per il vostro Sistema._

. _Interfaccia grafica_ (*GUI*):
.. Menu principale
.. Interfaccia di simulazione
.. Animazioni movimento pedine
.. Animazioni lancio dadi
.. Animazioni mazzo di carte
.. Leader board
. _Simulazione della partita:_
.. Simulazione di più partite in maniera rapida (senza visualizzazione dei turni, solo risultato finale)
.. Simulazione in multithread per partite multiple
. _Termine simulazione:_
.. Rieseguire simulazione più volte in modo rapido (mantenendo le stesse impostazioni)
.. Grafico storico punteggi dei vari giocatori durante la simulazione
.. Salvare report fine simulazione


=== B.3 Scenari d’uso dettagliati
_Descrivere gli scenari più comuni, più interessanti, o più complicati d’uso dei vostri servizi._

* *Analisi di dati in vari scenari*:
** Analizzare quanto il _valore dei dadi_ di un giocatore contribuisce sul suo _tasso di vincita_
** Analizzare come cambiano la _durata di ogni partita_ al _variare delle regole_
** Analizzare quali sono le _caselle più visitate_ dai vari giocatori
* *Gioco*:
** Eseguire _partite con un gruppo di giocatori_
** Giocare a _prevedere quale pedina vincerà_ la partita

=== B.4 Excluded Requirements
_Descrivere i servizi eventualmente i esclusi, e spiegare il perché_

. _Animazioni 3D:_
.. Animazioni lancio dadi in 3D (_Richiede l'uso di un engine 3D portando solo un miglioramento visivo, fuori dallo scopo del software_)
.. Animazioni mazzo di carte in 3D (_Richiede l'uso di un engine 3D portando solo un miglioramento visivo, fuori dallo scopo del software_)
. _Audio_
.. Effetti sonori (_Richiedono la creazione o licenza di effetti sonori portando solo un miglioramento visivo, fuori dallo scopo del software_)
. _Simulazione:_
.. Simulazione singola partita in multithread (_Non è richiesto eseguire simulazioni a velocità elevate per una singola partita, in più aumenta esponenzialmente la complessità del software potenzialmente senza alcun beneficio tangibile_)
.. Simulazione di più partite rapide con diverse impostazioni con gestione in coda (_Scenario estremo non di uso comune che può essere facilmente bypassato aspettando il termine delle varie simulazioni_)
. _Piattaforme di distribuzione:_
.. Piattaforme mobile (_Software principalmente simulatilo, uso in mobilità poco utile_)
.. Piattaforme web (_Implementazione web app fuori dagli scopi del progetto_)
. _Interazioni & Integrazioni:_
.. API (_Potenzialmente utile per automatization di task e integrazione in altri software ma fuori dallo scopo del progetto_)
.. Supporto a mod o plugin (_Potenzialmente utile per aggiungere funzionalità extra in modo rapido da parte dell'utente ma aumento della complessità e del rischio di introduzione di bug o vulnerabilità, con conseguente aumento della complessita per il supporto post rilascio_)

=== B.5 Assunzioni
_Documenta brevemente, in questa sezione, le ipotesi/decisioni sui requisiti più rilevanti che hai dovuto prendere durante il tuo progetto_

* Il _software_ è pensato come uno *strumento di simulazione* per tanto _l'interazione dell'utente_ durate una partita è ridotto al minimo;
* Il _software_ ha come obbiettivo solo quello di *ricavare i dati* dalle simulazione, non quello di aiutare l'utente ad _interpretarli_, per tanto la visualizzazione di essi potrebbe risultare parziale e non esaustiva. Per questo motivo *l'esportazione dei dati* risulta essere una funzionalità _relativamente importante_ per l'obbiettivo richiesto;
* Il _software_ è pensato per essere eseguito su *piattaforma PC* con _hardware relativamente moderno_ senza ottimizzazioni estensive sia dal punto di vista della _simulazione_ che della _GUI_;

=== B.6 Use Case Diagrams

#TODO

== C. Architettura Software
_SE PERTINENTE, riporta qui sia la vista statica che dinamica della progettazione del tuo sistema, in termini di diagramma dei componenti e i relativi diagrammi di sequenza._

=== C.1 La visione statica del sistema: Diagramma dei Componenti

#TODO

=== C.2 La visione dinamica dell'architettura software: Sequence Diagram

#TODO

== D. Dati e loro modellazione  (se il sistema si interfaccia con un DBMS)
_Definite le sorgenti di dati a voi necessarie per realizzare I servizi di cui sopra. Modellate tali dati tramite un ER o similari. Specificate se e quali di tali dati sono gia’ forniti da applicativi esistenti._

*Il sistema non fa uso di DBMS.*

== E. Scelte Progettuali (Design Decisions)
_Documenta qui le 5 decisioni progettuali più importanti che hai dovuto prendere. È possibile utilizzare sia una specifica testuale che schematica._

#TODO

== F. Progettazione di Basso Livello

#TODO

== G. Spiegare come il progetto soddisfa i requisiti funzionali (RF) e quelli non funzionali (RNF)
_Riporta in questa sezione in che modo la progettazione architettonica e di basso livello prodotta soddisfa gli RF e gli RNF._

#TODO

== Appendice. Prototipo
_Fornisci un breve rapporto sul tuo prototipo e in particolare: informazioni su ciò che hai implementato, come l'implementazione copre RF e RNF, come i prototipi dimostrano la correttezza del tuo progetto rispetto a RF e RNF. Puoi aggiungere alcuni screenshot per descrivere quanto richiesto sopra. Preparati a mostrare il tuo prototipo durante l'esame orale._

#TODO